name: Build SM64 Decomp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git zlib1g-dev libbz2-dev libssl-dev libffi-dev libgmp-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

        # Install QEMU-IRIX
        sudo apt-get install -y qemu-system-mips
        git clone https://github.com/n64decomp/qemu-irix.git
        cd qemu-irix
        make -j$(nproc)
        sudo make install

    - name: Clone SM64 Decomp Repository
      run: |
        git clone https://github.com/n64decomp/sm64.git
        cd sm64

    - name: Build SM64 Decomp
      run: |
        make clean
        make -j$(nproc)

    - name: Archive SM64 Decomp
      uses: actions/upload-artifact@v2
      with:
        name: sm64-decomp
        path: sm64
